    version: "3.8"
    services:
        api:
            image:
                img-srodenas-api-employee-ktor
            build:     #Le dice a Docker, que hay que construirla primero, antes de lanzarla.
                context: ..   #El DockerFile, está en la carpeta inferior

            container_name: api-employee-ktor
            ports:
                - "8081:8081"
            depends_on:
                db:
                    condition: service_healthy  #Tenemos que esperar a que MariaDB se arranque primero.
                    # Hasta que Docker, no marque al contenedor MAriaDB como healthy, api-employee-ktor no arranca.
            environment:
                DATABASE_URL: "jdbc:mariadb://db:3306/dbEmployee"
                DATABASE_USER: "santi"
                DATABASE_PASSWORD: "santi"
            networks:
                - ktor-network


        db:
            image: mariadb:latest
            container_name: ktor-mariadb
            restart: always  #queremos que se reinicie, si Docker se reinicia.

            ports:
                - "3306:3306"
            command: --default-authentication-plugin=mysql_native_password
            environment:
                MYSQL_DATABASE: dbEmployee
                MYSQL_USER: santi  #usuario santi
                MYSQL_PASSWORD: santi #contraseña del usuario santi
                MYSQL_ROOT_PASSWORD: santiago #contraseña del root
            volumes:
                - ./dump:/docker-entrypoint-initdb.d
                - ./conf:/etc/mysql/conf.d
                - persistent:/var/lib/mysql
            networks:
                - ktor-network

            #Puesto que hemos puesto a la api y phpmyadmin en service_healthy, el contenedor de MariaDb
            #   debe ejecutar un healthcheck, que verifica si el servicio está funcionando correctatmente.
            #   Es una prueba que me ha obligado a hacer.
            # Hasta que Docker, no marque al contenedor MAriaDB como healthy, los otros contenedores no arrancarán.

            #El contenedor antes de lanzarse, comprueba si MariaDB está funcionando
            #Tiene que hacer una prueba dentro del contenedor en localhost.
            #Para ello, realiza una serie de test. Dentro del contenedor, le hace un ping a
            #   Hará el test cada 10 sg.
            #   Lo hará 5 veces, en caso de que no conteste.
            #   Se esperará 10s antes de empezar a realizar el test. Se supone que tarda un ratejo en arrancar:
            #   Se espera 5sg a la respuesta, para considerarla fallida.
            healthcheck:
                test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
                interval: 10s
                retries: 5
                start_period: 10s
                timeout: 5s

        phpmyadmin:
            image: phpmyadmin/phpmyadmin
            container_name: ktor-phpmyadmin
            restart: always   #queremos que se reinicie, si Docker se reinicia.

            depends_on:
                db:
                    condition: service_healthy  #Tenemos que esperar a que MariaDB se arranque primero.
                    # Hasta que Docker, no marque al contenedor MAriaDB como healthy, ktor-phpmyadmin no arranca.
            ports:
                - 8000:80
            environment:
                PMA_HOST: db
                MYSQL_ROOT_PASSWORD: santiago #contraseña del root
            networks:
                - ktor-network

    networks:
        ktor-network:
            driver: bridge
    volumes:
        persistent:

    #docker-compose down -v    #para que borre también los volúmenes en el caso de que quiera volver a lanzarlo.
    #docker-compose up -d  --build   #para levantarlos, pero que construya antes la de la api.